  #                                      PYTHON ASSIGNMENT

## NAME: B.KEERTHIGA
## REG NO: 21UAI046
## DEPT: AI & DS

## Write a function called show stars(rows)

In [38]:
row = 5
for i in range(0, row):
    for j in range(0, i + 1):
        print("*", end=' ')
    print("\r")

* 
* * 
* * * 
* * * * 
* * * * * 


## Write a program to remove characters from a string starting from zero up to n and return a new string

In [39]:
sym = [';', ':', '!', "*", " "]
string = "k;e:e!r*t;h!i:g:a"
print ("Original String : " , string)
for i in sym :
    string = string.replace(i, '')
print ("Resultant list is : " , str(string))

Original String :  k;e:e!r*t;h!i:g:a
Resultant list is :  keerthiga


## Iterate the given list of numbers and print only those numbers which are divisible by 5



In [40]:
b=[1,2,3,4,5,6,7,8,9,10]
for i in b:
    if(i%5==0):
        print('the value is :',i)
    else :
        continue

the value is : 5
the value is : 10


## Write a program to find how many times substring “Hi” appears in the given string

In [41]:
a=input("enter the string:")
print("the number of times the word hi is displayed is : ",a.count('hi'))

enter the string:hi hi hi
the number of times the word hi is displayed is :  3


## Print the following pattern
## 1 
## 2 2 
## 3 3 3 
## 4 4 4 4 
## 5 5 5 5 5


In [42]:
row = 6
for i in range(row):
    
    for j in range(i):
        print(i, end=' ')
    print('')


1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


#                                              LIST

## Python program to interchange first and last elements in a list

In [43]:
def swapL(sl):
    n = len(sl)
      
    # Swapping 
    temp = sl[0]
    sl[0] = sl[n - 1]
    sl[n - 1] = temp
      
    return sl
      
l = [19, 14, 6, 9, 56, 10]

print(l)
print("Swapped list: ",swapL(l))

[19, 14, 6, 9, 56, 10]
Swapped list:  [10, 14, 6, 9, 56, 19]


## Python program to swap two elements in a list

In [44]:
def swapL(sl,pos1,pos2):
    n = len(sl)     
    # Swapping 
    temp = sl[pos1]
    sl[pos1] = sl[pos2]
    sl[pos2] = temp
    return sl      

l= [10, 14, 5, 9, 56, 12]
pos1= 2
pos2= 5

print(l)
print("Swapped list: ",swapL(l,pos1-1,pos2-1))


[10, 14, 5, 9, 56, 12]
Swapped list:  [10, 56, 5, 9, 14, 12]


## Python  Ways to find length of list

In [45]:
inp = ['Python','Java','c','Machine Learning','c++']
size = len(inp)
print(size)

5


## Maximum of two numbers in Python

In [46]:
a = [2,2,5,6,9]

  
maximum = max(a )
print(maximum)

9


## Minimum of two numbers in Python

In [16]:
a = [2,2,5,6,9]

  
minimum = min(a )
print(minimum)

2


## STRING

## Python program to check whether the string is Symmetrical or Palindrome

In [51]:
a=(input("enter the string:"))
x=a[::-1]
if a==x:
    print('the given string is a pallindrome')
else:
    print('it is not a pallindrome')


enter the string:hi
it is not a pallindrome


## Reverse words in a given String in Python

In [52]:
string = "Hi im keerthiga"

s = string.split()[::-1]
l = []
for i in s:
    
    l.append(i)

print(" ".join(l))

keerthiga im Hi


## Ways to remove i’th character from string in Python

In [53]:
def removechar(str1, n): 
   x = str1[ : n]   
   y = str1[n + 1: ]
   return x + y
if __name__ == '__main__':
   str1 = input("Enter a string ::")
   n = int(input("Enter the index to remove ::"))
   print("The new string is ::")
   print(removechar(str1, n))

Enter a string ::keerthiga
Enter the index to remove ::1
The new string is ::
kerthiga


# TUPLE

## Python program to Find the size of a Tuple

In [54]:
a=(1,2,3,4,5)
b=a.__sizeof__()
b

64

## Python – Maximum and Minimum K elements in Tuple

In [55]:
a=(1,2,3,4,5)
x=max(a)
y=min(a)
print(x)
print(y)

5
1


## Python – Sum of tuple elements

In [56]:
a=(13,13)
x=sum(a)
print(x)

26


## DICTIONARY

## Python | Sort Python Dictionaries by Key or Value

In [27]:
#by keys

d={"key1":"1","key3":"5","key2":"4"}
print(sorted(d))


['key1', 'key2', 'key3']


In [57]:
#by values 

dict1 = {1: 1, 10: 9, 2: 4}
sorted_values = sorted(dict1.values()) 
sorted_dict = {}

for i in sorted_values:
    for k in dict1.keys():
        if dict1[k] == i:
            sorted_dict[k] = dict1[k]
            break

print(sorted_dict)

{1: 1, 2: 4, 10: 9}


## Python dictionary with keys having multiple inputs

In [58]:
import random as r
dict = {}
 
x, y, z = 10, 20, 30
dict[x, y, z] = x + y - z;
 
x, y, z = 5, 2, 4
dict[x, y, z] = x + y - z;
 
print(dict)

{(10, 20, 30): 0, (5, 2, 4): 3}


# SET

## Find the size of a Set in Python

In [59]:
a={1,2,3,4,5,6}
a.__sizeof__()

456

## Iterate over a set in Python

In [60]:
a={1,2,3,4,5,6,7}
for i in a:
    print('the element is :',i)

the element is : 1
the element is : 2
the element is : 3
the element is : 4
the element is : 5
the element is : 6
the element is : 7


# MATRIX

## Python – Assigning Subsequent Rows to Matrix first row elements

In [61]:
list = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
print("The original list : ",str(list))
res = {list[0][ele] :  list[ele + 1] for ele in range(len(list) - 1)}
print("The Assigned Matrix : ", str(res))

The original list :  [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
The Assigned Matrix :  {1: [4, 5, 6], 2: [7, 8, 9], 3: [10, 11, 12]}


## Adding and Subtracting Matrices in Python

In [62]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
print("Addition of two matrix")
print(np.add(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]


# FUNCTIONS

## How to get list of parameters name from a function in Python?

In [63]:
def fun(b,c
       ):
    return a**b 
import inspect  
print(inspect.signature(fun))

(b, c)


## How to Print Multiple Arguments in Python?

In [64]:
def a(name, nam1):
    print("Hi im", name +', ' , nam1)
a("keerthiga", "welcome")

Hi  keerthiga,  welcome
